### ISSUE TITLE
[New Sensor]: ARRI ALEXA 35

### ISSUE THREAD

**Issue by michalfratczak** [EmberLightVFX/Camera-Sensor-Database#14]
### References

https://www.arri.com/en/camera-systems/cameras/alexa-35#273064

### Vendor

ARRI

### Camera

ALEXA 35

### Auto-generate sensor sizes

- [ ] Do auto-generate sensor sizes

### Name

4.6K 3:2 Open Gate

### Resolution

4608 x 3164

### Sensor size (mm)

28.0 x 19.2

### Name

4.6K 16:9

### Resolution

4608 x 2592

### Sensor size (mm)

28.0 x 15.7

### Name

4K 16:9

### Resolution

4096 x 2304

### Sensor size (mm)

24.9 x 14.0

### Name

4K 2:1

### Resolution

4096 x 2048

### Sensor size (mm)

24.9 x 12.4

### Name

3.8K 16:9

### Resolution

3840 x 2160

### Sensor size (mm)

23.3 x 13.1

### Name

3.3K 6:5

### Resolution

3328 x 2790

### Sensor size (mm)

20.22 x 16.95

### Name

3K 1:1

### Resolution

3072 x 3072

### Sensor size (mm)

18.7 x 18.7

### Name

2.7K 8:9

### Resolution

2743 x 3086

### Sensor size (mm)

16.7 x 18.7

### Name

2K 16:9 S16

### Resolution

2048 x 1152

### Sensor size (mm)

12.4 x 7.0

**Comment by ManuelHouben** [comment]
It appears that some of these values are rounded in the listed source - ARRI gives a Sensor Maximum Size of 27.99 x 19.22 mm / 1.102 x 0.757" and diagonal Ø 33.96 mm / 1.337". The diagonal itself would hint at a rounding error/omission of exact values in length and width of the sensor, however the values should be sufficiently accurate for VFX applications.
More accurate values can be found using the [Frame Line & Lens Illumination Tool](https://tools.arri.com/flt/index.html).
These are as follows:
- 4.6K 3:2 Open Gate
27.99 x 19.22 mm
- 4.6K 16:9
27.99 x 15.75 mm
- 4K 16:9
24.88 x 14.00 mm
- 4K 2:1
24.88 x 12.44 mm
- 3.8K 16:9
23.33 x 13.12 mm
- 3.3K 6:5
20.22 x 16.95 mm
- 3K 1:1
18.66 x 18.66 mm
- 2.7K 8:9
16.66 x 18.75 mm
- 2K 16:9 S16
12.44 x 7.00 mm

I was made aware of this by a colleague who told me not to trust any values found in marketing materials or on third party websites and so to retain trust with similarly fashioned people the values should be as accurate as possible, I guess.
