### ISSUE TITLE
[New Sensor]: Phantom Flex 4k

### ISSUE THREAD

**Issue by ridindave** [EmberLightVFX/Camera-Sensor-Database#16]
### References

https://www.lovehighspeed.com/wp-content/uploads/2017/01/Flex4K-Manual-Rev2.pdf

### Vendor

Other

### Other Vendor

Vision Research

### Camera

Phantom FLex 4k

### Additional Information

High speed camera

### Auto-generate sensor sizes

- [X] Do auto-generate sensor sizes

### Name

4k 16/9 (full sensor)

### Resolution

4096 x 2304

### Sensor size (mm)

27.6 x 15.5

### Name

4k 1.85

### Resolution

4096 x 2216

### Name

4k DCI (1.89)

### Resolution

4096 x 2160

### Name

UHD 16/9

### Resolution

3840 x 2160

### Name

4k 2.39

### Resolution

4096 x 1712

### Name

4k anamorphic x2

### Resolution

2752 x 2304

**Comment by EmberLightVFX** [comment]
Thanks for the submission! I saw in the pdf that there were 4K and 2K modes for the camera so I re-did your submissing with all options to cover all grounds. I closed your PR but your submission have helped continue making the DB bigger and better :) Thanks!

**Comment by ridindave** [comment]
> On 10 Oct 2024, at 00:25, Ember Light ***@***.***> wrote:
> 
> 
> Thanks for the submission! I saw in the pdf that there were 4K and 2K modes for the camera so I re-did your submissing with all options to cover all grounds. I closed your PR but your submission have helped continue making the DB bigger and better :) Thanks
> 
> 
Thanks to you for correcting my submission! 


Best,

David
